apiVersion: v1
kind: Service
metadata:
  name: app-service-2
  labels:
    app: app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31200
  selector:
    app: app
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service-2
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
      tier: frontend
  template:
    metadata:
      labels:
        app: app
        tier: frontend
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
      - name: app
        image: phionify/laravel-fpm
        env:
          - name: DB_HOST
            value: app-mysql
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "(php artisan route:cache || true) && (php artisan migrate || true)
                         && (ln -sf /app /var/www/html || true) "]
        volumeMounts:
          - name: shared-data
            mountPath: /var/www
        ports:
          - containerPort: 9000
            name: php
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 80
            name: nginx
        volumeMounts:
          - name: shared-data
            mountPath: /var/www
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf