apiVersion: v1
kind: Service
metadata:
  name: app-mysql
  labels:
    app: app
spec: 
  ports:
    - port: 3306
  selector:
    app: app
    tier: mysql
  clusterIP: None

---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: app-mysql
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
        tier: mysql
    spec:
      containers:
      - image: mariadb
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "secret"
          - name: MYSQL_DATABASE
            value: "laravel"
          - name: MYSQL_USER
            value: "devops"
          - name: MYSQL_PASSWORD
            value: "12345"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage-2
          mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-persistent-storage-2
        persistentVolumeClaim:
          claimName: mysql-claim-2